2024-08-08 10:35:03.080178 - rocketbot - INFO - request: N-IntegracionApiAtomox : line 16.3 - rpaconnect : request  id: 9670fda5-df5b-c859-63f6-3f61f1f71489 -  - {"method":"post","url":"{api_cloudsigner}","json":"{\n  \"codigoContrato\": \"{contrato}\",\n  \"nombreDocumento\": \"{documento}\",\n  \"firmantes\": \"{firmantes}\",\n  \"firmados\": \"{firmados}\",\n  \"faltantes\": \"{faltantes}\",\n  \"estado\": \"{estado}\"\n}","params":"","form":"","proxy":"","file":"","header":"{\"X-Api-Key\":\"{api_key}\"}"}
2024-08-08 10:35:03.089137 - Rocketbot - ERROR - EXCEPTION IN (<string> Rocketbot, L_108 ""): MissingSchema: Invalid URL '{api_cloudsigner}': No schema supplied. Perhaps you meant http://{api_cloudsigner}?
2024-08-08 10:35:18.402120 - rocketbot - INFO - request: N-IntegracionApiAtomox : line 16.3 - rpaconnect : request  id: 9670fda5-df5b-c859-63f6-3f61f1f71489 -  - {"method":"post","url":"{api_cloudsigner}","json":"{\n  \"codigoContrato\": \"{contrato}\",\n  \"nombreDocumento\": \"{documento}\",\n  \"firmantes\": \"{firmantes}\",\n  \"firmados\": \"{firmados}\",\n  \"faltantes\": \"{faltantes}\",\n  \"estado\": \"{estado}\"\n}","params":"","form":"","proxy":"","file":"","header":"{\"X-Api-Key\":\"{api_key}\"}"}
2024-08-08 10:35:39.457239 - Rocketbot - ERROR - EXCEPTION IN (<string> Rocketbot, L_108 ""): ConnectTimeout: HTTPConnectionPool(host='54.88.59.194', port=8081): Max retries exceeded with url: /api/v1.0/sourcings/documentos (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E48C2921A0>, 'Connection to 54.88.59.194 timed out. (connect timeout=None)'))
